'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.7905
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\Others\ieclone.mdb;P"& _ 
            "ersist Security Info=True")>  _
        Public ReadOnly Property iecloneConnectionString() As String
            Get
                Return CType(Me("iecloneConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString), _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=Umbrella;Persist Security Info=True;User " & _
            "ID=sa;Password=123")> _
        Public ReadOnly Property UmbrellaConnectionString() As String
            Get
                Return CType(Me("UmbrellaConnectionString"), String)
            End Get
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Configuration.SettingsDescriptionAttribute("Save User name on Exit"), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Unknown User")> _
        Public Property Username() As String
            Get
                Return CType(Me("Username"), String)
            End Get
            Set(ByVal value As String)
                Me("Username") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property Audio() As String
            Get
                Return CType(Me("Audio"), String)
            End Get
            Set(ByVal value As String)
                Me("Audio") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Checked")> _
        Public Property ChkSound() As Global.System.Windows.Forms.CheckState
            Get
                Return CType(Me("ChkSound"), Global.System.Windows.Forms.CheckState)
            End Get
            Set(ByVal value As Global.System.Windows.Forms.CheckState)
                Me("ChkSound") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")> _
        Public Property WindowPosition() As Global.System.Drawing.Point
            Get
                Return CType(Me("WindowPosition"), Global.System.Drawing.Point)
            End Get
            Set(ByVal value As Global.System.Drawing.Point)
                Me("WindowPosition") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("349, 505")> _
        Public Property WindowSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("WindowSize"), Global.System.Drawing.Size)
            End Get
            Set(ByVal value As Global.System.Drawing.Size)
                Me("WindowSize") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property WindowState() As String
            Get
                Return CType(Me("WindowState"), String)
            End Get
            Set(ByVal value As String)
                Me("WindowState") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property Period() As String
            Get
                Return CType(Me("Period"), String)
            End Get
            Set(ByVal value As String)
                Me("Period") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property SystemDate() As String
            Get
                Return CType(Me("SystemDate"), String)
            End Get
            Set(ByVal value As String)
                Me("SystemDate") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property FinancialPeriod() As String
            Get
                Return CType(Me("FinancialPeriod"), String)
            End Get
            Set(ByVal value As String)
                Me("FinancialPeriod") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property IPAddress() As String
            Get
                Return CType(Me("IPAddress"), String)
            End Get
            Set(ByVal value As String)
                Me("IPAddress") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property LastOpenedInstitute() As String
            Get
                Return CType(Me("LastOpenedInstitute"), String)
            End Get
            Set(ByVal value As String)
                Me("LastOpenedInstitute") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property LastOpenedInstituteID() As String
            Get
                Return CType(Me("LastOpenedInstituteID"), String)
            End Get
            Set(ByVal value As String)
                Me("LastOpenedInstituteID") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("System")> _
        Public Property InstituteDefaultPage() As String
            Get
                Return CType(Me("InstituteDefaultPage"), String)
            End Get
            Set(ByVal value As String)
                Me("InstituteDefaultPage") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Task")> _
        Public Property LibraryDefaultPage() As String
            Get
                Return CType(Me("LibraryDefaultPage"), String)
            End Get
            Set(ByVal value As String)
                Me("LibraryDefaultPage") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("System")> _
        Public Property PayrollDefaultPage() As String
            Get
                Return CType(Me("PayrollDefaultPage"), String)
            End Get
            Set(ByVal value As String)
                Me("PayrollDefaultPage") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Show")> _
        Public Property InstituteSystemPanel() As String
            Get
                Return CType(Me("InstituteSystemPanel"), String)
            End Get
            Set(ByVal value As String)
                Me("InstituteSystemPanel") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Show")> _
        Public Property InstituteAdmissionPanel() As String
            Get
                Return CType(Me("InstituteAdmissionPanel"), String)
            End Get
            Set(ByVal value As String)
                Me("InstituteAdmissionPanel") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Show")> _
        Public Property InstituteFeesPanel() As String
            Get
                Return CType(Me("InstituteFeesPanel"), String)
            End Get
            Set(ByVal value As String)
                Me("InstituteFeesPanel") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Show")> _
        Public Property InstituteExaminationPanel() As String
            Get
                Return CType(Me("InstituteExaminationPanel"), String)
            End Get
            Set(ByVal value As String)
                Me("InstituteExaminationPanel") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Show")> _
        Public Property InstituteActivityPanel() As String
            Get
                Return CType(Me("InstituteActivityPanel"), String)
            End Get
            Set(ByVal value As String)
                Me("InstituteActivityPanel") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Show")> _
        Public Property LibrarySystemPanel() As String
            Get
                Return CType(Me("LibrarySystemPanel"), String)
            End Get
            Set(ByVal value As String)
                Me("LibrarySystemPanel") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Show")> _
        Public Property LibraryTaskPanel() As String
            Get
                Return CType(Me("LibraryTaskPanel"), String)
            End Get
            Set(ByVal value As String)
                Me("LibraryTaskPanel") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Show")> _
        Public Property PayrollSystemPanel() As String
            Get
                Return CType(Me("PayrollSystemPanel"), String)
            End Get
            Set(ByVal value As String)
                Me("PayrollSystemPanel") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Show")> _
        Public Property PayrollPeriodicPanel() As String
            Get
                Return CType(Me("PayrollPeriodicPanel"), String)
            End Get
            Set(ByVal value As String)
                Me("PayrollPeriodicPanel") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Show")> _
        Public Property PayrollProvidentFundPanel() As String
            Get
                Return CType(Me("PayrollProvidentFundPanel"), String)
            End Get
            Set(ByVal value As String)
                Me("PayrollProvidentFundPanel") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property ChatName() As String
            Get
                Return CType(Me("ChatName"), String)
            End Get
            Set(ByVal value As String)
                Me("ChatName") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Umbrella.My.MySettings
            Get
                Return Global.Umbrella.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
